# Generated by Django 5.2.1 on 2025-08-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_to_display',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions to randomly display to students. Leave blank to use all questions.'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='selected_questions',
            field=models.ManyToManyField(blank=True, help_text='Questions randomly selected for this attempt', to='exams.question'),
        ),
    ]
