# Generated by Django 5.2.1 on 2025-08-08 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_questions_to_display_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fullstack', 'Full Stack Web Development'), ('frontend_react', 'Frontend Development with React.js'), ('backend_django', 'Backend Development with Python Django'), ('backend_fastapi', 'Backend Development with FastAPI'), ('data_analysis', 'Data Analysis'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('ui_ux', 'UI/UX Design'), ('mobile_dev', 'Mobile Development')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField(default=12, help_text='Course duration in weeks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.course'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course', 'name')},
        ),
    ]
